neo4j_uri: "neo4j+s://2d0ba965.databases.neo4j.io"
neo4j_user: "neo4j"
neo4j_password: "s6U3ceTXtwDpbCoseX-up6-8Icrgsi--Ga3bkT5zh50"
pinecone_api_key: "pcsk_28Vf2V_EA58qAT2erydDN2HCKSM422mfZYmwoe2d4zxYLSiV87sarN4pj8XVhnxtzFJqk7"

